name: Deploy to AWS Docker on merge
on:
    push:
        branches:
            - prod
jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup QEMU
              uses: docker/setup-qemu-action@v2
            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_TOKEN }}
            - name: Build and Push
              uses: docker/build-push-action@v4
              with:
                  context: .
                  push: true
                  tags: ${{ secrets.DOCKER_HUB_USERNAME }}/frontend-project:latest
    deploy:
        runs-on: ubuntu-latest
        needs: docker
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Copy file via SSH
              uses: appleboy/scp-action@v0.1.4
              with:
                  host: ${{ secrets.HOST_SERVER }}
                  username: ${{ secrets.HOST_USER_NAME }}
                  key: ${{ secrets.HOST_SSH_PRIVATE_KEY }}
                  port: 22
                  source: "docker-compose.yml"
                  target: "/home/ubuntu/frontend"
            - name: Run docker compose via SSH
              uses: appleboy/ssh-action@v0.1.10
              with:
                  host: ${{ secrets.HOST_SERVER }}
                  username: ${{ secrets.HOST_USER_NAME }}
                  key: ${{ secrets.HOST_SSH_PRIVATE_KEY }}
                  port: 22
                  script: |
                      cd /home/ubuntu/frontend
                      echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
                      docker compose down
                      docker compose pull
                      docker compose up -d
                      rm -rf /home/ubuntu/frontend